### ISSUE TITLE
Fungerande formulär

### ISSUE THREAD

**Issue by VSMC** [ZoCom-utbildning/folkans-it-utbildningar#21]
- [x] Fråge kort
- [ ] multi-step funktion
- [ ] nummer på fråga
- [ ] fram och bakåt knappar
- [ ] nav/hamburger meny
- [ ] multi-step animationer
- [ ] range slider
- [ ] checkbox knapp
- [ ] kort styling
- [ ] desktop kort vy
- [ ] desktop bild komponent
